### ISSUE TITLE
Ruby 2.7+ required but Puppet 6 doesn't run on Ruby 2.7

### ISSUE THREAD

**Issue by ekohl** [puppetlabs/puppetlabs_spec_helper#372]
AFAIK Puppet 6 doesn't run on Ruby 2.7. I'd expect either Ruby 2.5 + Puppet 6 or Ruby 2.7 + Puppet 7. However, given Puppet 6 is not yet EOL I'd prefer to have Ruby 2.5 as the lower bound.

_Originally posted by @ekohl in https://github.com/puppetlabs/puppetlabs_spec_helper/pull/364#discussion_r1084092481_

**Comment by chelnak** [comment]
Yeah you are right..

Lets get that fixed.. hopefully there are no major dependency issues.
